config/routes.rb
OpenMindMap::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :news

  resources :bugs

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations => "registrations"}
  
  get "maps/public"
  get "maps/import"
  post "maps/import"
  resources :maps do
    resources :versions
    member do
      post 'share'
      get  'share'     
      post 'event'             
    end
    resources :attachments 
    resources :nodes do 
      resources :attachments 
    end
    resources :contacts

  end
  
  resources :contacts do
    get :autocomplete_user_email, :on => :collection
  end
  
  match ':controller(/:action(/:id(.:format)))'

  root :to => "maps#index"

end

app/models/map.rb
class Map < ActiveRecord::Base
  belongs_to :user
  belongs_to :last_editor, :foreign_key => "last_edit_by", :class_name => "User"
  has_and_belongs_to_many :users, :uniq => true 
  has_many :attachments
  versioned
  
  require 'pp'
  before_save :clean_svg

  def clean_svg
    opts = {}
    opts[:grid] = true
    opts[:absolute] = true
    svgdata = Nokogiri::XML(self.svgdata)
    svgdata.xpath("//*[contains(@style,'opacity: 0')]").each {|x| x.remove}
    self.svgdata = svgdata.to_s    
  end

  def self.public
    find_all_by_isPublic(true) || []
  end

  def self.from_freemind xml
  	map = self.new
  	xml_map = Nokogiri::XML(xml)
  	content = {}
  	nodes = []
  	nodes_from_xml = xml_map.xpath('/map/node')
  	connections = {}  	
  	unless nodes_from_xml.empty?
	    root_node =  get_node_data(nodes_from_xml)	    
      nodes << root_node
      map.title = root_node["text"]
	    nodes += get_child_nodes(nodes_from_xml) if nodes_from_xml.children
	  end
  	map.content = {"nodes" => nodes, "connections" => connections}.to_json    
  	map.save
  	map
  end

private
  def self.get_child_nodes xml_node
    nodes = []
    unless xml_node.children.empty?
      parent = get_node_data(xml_node)
		  xml_node.children.each do |node|		    
		    node_data = get_node_data(node, parent)
  			nodes << node_data unless node_data.empty?
  			if node.children
  			  nodes += get_child_nodes(node)
  			end
  		end  		
  	end
  	nodes  		
  end
  
  def self.get_node_data node, parent=nil
    node_hash = {}
    node_hash["text"] = node.attribute('TEXT').value if node.attribute('TEXT')
    node_hash["guid"] = node.attribute('ID').value   if node.attribute('ID')
    node_hash["rel_position"] = node.attribute('POSITION').value if node.attribute('POSITION')
    unless node_hash.empty?
      if parent 
  	    node_hash["parentGUID"] = parent["guid"]           
  	  else
  	    node_hash["isroot"] = true 
  	  end
  	  node_hash["position"]  	 
    end       
	  node_hash
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_filter :authenticate_user!, :except => [:public, :show, :index]
  layout :resolve_layout

  require 'base64'
  # GET /maps
  # GET /maps.xml
  def index
    unless current_user
      @maps = Map.public
      render :action => "public"
      return
    end
    @maps = current_user.maps
    @shared_maps = current_user.shared_maps
    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @maps }  
    end
  end

  def event
    if 'user-connected' == params[:event]
      push = $redis.lrange "map#{params[:id]}", 0, -1
    else
      $redis.rpush "map#{params[:id]}", {:event => params[:event], :data => params[:data]}.to_json
      push = Pusher["map-#{params[:id]}"].trigger(params[:event], params[:data])
    end

    respond_to do |format|
      format.json { render :json => {:status => push} }
    end
  end

  def import
    if request.post?
      uploaded_io = params[:freemind_file]      
      @map = Map.from_freemind(uploaded_io.read)
      @map.user = current_user      
      respond_to do |format|
        if @map.save
          format.html { redirect_to(edit_map_path(@map), :notice => 'Map was successfully created.') }          
        else
          format.html
        end
      end    
    end
  end
  
  def public
     @maps = Map.public
     respond_to do |format|
       format.html # index.html.erb
       format.json  { render :json => @maps }
     end     
  end
  
  def shared
     @maps = Map.public
     respond_to do |format|
       format.html # index.html.erb
       format.json  { render :json => @maps }
     end     
  end
  
  # GET /maps/1
  # GET /maps/1.json
  # GET /maps/1.svg
  def show
    @container_class = 'container-fluid'
    @map = Map.find(params[:id], :include => [:attachments, :users])
    unless @map.isPublic || (current_user && @map.user == current_user || @map.users.include?(current_user))
      return render :file => "public/401.html", :status => :unauthorized      
    end
    @readOnly  = true
    respond_to do |format|
      format.html # show.html.erb
      format.svg  do
        if @map.svgdata
          render :inline => @map.svgdata 
        else
          render :inline => '<svg />'
        end
      end
      format.json { render :json => @map.to_json(:include => [:attachments, :users]) }      
    end
  end

  def share
    @map = Map.find(params[:id])
    if request.post?
      @map.skip_version do
        @map.update_attribute(:isPublic, params[:public] == 'true')
        @saved = @map.save        
      end
      respond_to do |format|
        format.json { render :json => {:public => @map.isPublic, :status => @saved } }
      end
    else
      respond_to do |format|
        format.json { render :json => @map.isPublic }
      end
    end    
  end

  # GET /maps/new
  # GET /maps/new.json
  def new
    @map = Map.new
    @container_class = 'container-fluid'
    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @map }
    end
  end

  # GET /maps/1/edit
  def edit    
    @container_class = 'container-fluid'
    @map = Map.find(params[:id])    
  end

  # POST /maps
  # POST /maps.json
  def create
    unless ['dialoguemap', 'mindmap'].include?(params[:map][:conf])
      redirect_to :action => :new, :notice => 'There is a problem with the new map'
    end

    
    @map = Map.new(params[:map])
    case params[:map][:conf]
      when 'dialoguemap' then @map.content = '{"nodes":[{"position":{"x":50,"y":324},"size":{"w":100,"h":60},"text":"New map","radius":10,"style":"OpenMindMap.node.ibis.question","isroot":true}],"connections":{},"images":[]}'
      when 'mindmap' then @map.content = '{"nodes":[{"position":{"x":4000,"y":3000},"size":{"w":100,"h":60},"text":"New map","radius":10,"style":"OpenMindMap.node.classic","isroot":true}],"connections":{},"images":[]}'
    end
    @map.user = current_user
    
    respond_to do |format|
      if @map.save
        format.html { redirect_to(edit_map_url(@map), :notice => 'Map was successfully created.') }
        format.json  { render :json => @map, :status => :created, :location => @map }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /maps/1
  # PUT /maps/1.json
  def update
    @map = Map.find(params[:id])
    if params[:map][:users] && params[:map][:users][:user_email]
      @user = User.find_by_email(params[:map][:users][:user_email])
      if @user
        @map.users << @user
      end
      params[:map].delete(:users)
    end
    params[:map][:last_edit_by] = current_user.id
    if params[:versioning]
      map_saved = @map.update_attributes(params[:map])
    else
      @map.skip_version do
        map_saved = @map.update_attributes(params[:map])
      end
    end
    respond_to do |format|
      if map_saved
        if params[:map][:content]
          $redis.del "map#{params[:id]}"
        end
        format.html { redirect_to(@map, :notice => 'Map was successfully updated.') }
        format.json  { render :json => @map.to_json({:methods => [:version]}), :status => :ok }
        format.js 
      else
        format.html { render :action => "edit" }
        format.json { render :json => @map.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /maps/1
  # DELETE /maps/1.xml
  def destroy
    @map = Map.find(params[:id])
    @map.destroy if (@map.user == current_user)
    respond_to do |format|
      format.html { redirect_to(maps_url) }
      format.json  { head :ok }
    end
  end

private

  def resolve_layout
    case action_name
    when "edit"
      "maps_editor"
    else
      "application"
    end
  end

end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_dialogs.html.erb
<div id='placeHolder' style='display:none; position:absolute;'><textarea id='inputBox' style='background-color:transparen'></textarea></div>
<div id="wiki" class="curtain boxed hide"></div>
<div id="clipart" class="curtain boxed hide">
	<button class='btn' onClick='toggleClipartLibrary()'>Close</button>
	<ul class="thumbnails">
		   
	</ul>	
</div>

<div id="backgounds" class="curtain boxed hide">
	<button class='btn' onClick='toggleBackgroundLibrary()'>Close</button>
	<button class='btn' onClick='resetBackgroundImage()'>Remove background</button>
	<ul class="thumbnails"> 
	</ul>	
</div>

<div id="attachment-modal" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close" data-dismiss="modal">&times;</a>
    <h3 id='attachment_title'></h3>
  </div>
  <div class="modal-body">
 	<p></p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn close" data-dismiss="modal">Close</a>
  </div>
</div>

<div id="youtube-modal" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close" data-dismiss="modal">&times;</a>
    <h3>Search for YouTube video</h3>
  </div>
  <div class="modal-body">
 	<p><label for="yt-query">Terms </label><input class="search" type="text" name="yt-query" id="yt-query" /></p>
	<input type='hidden' id='guid' />
  </div>
  <div class="modal-footer">
    <a href="#" class="btn close" data-dismiss="modal">Confirm</a>
  </div>
</div>

<div id="colorpickerHolder" style="position: absolute;"></div>

<% if @map.id %>
<div id="versioning-modal" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close" data-dismiss="modal">&times;</a>
    <h3>Map versioning</h3>
  </div>
  <div class="modal-body">
 	<p></p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn close" data-dismiss="modal">Cancel</a>
  </div>
</div>

<div id="invite-user-modal" class="modal hide fade">
  <div class="modal-header">
    <a href="#" class="close" data-dismiss="modal">&times;</a>
    <h3>Share map with user</h3>
  </div>
  <div class="modal-body">
 	<p>
		<%= form_for @map, :remote => true do |f| %>	
			<%= f.fields_for :users do |user_form| %>
		 		<%= user_form.autocomplete_field :user_email, autocomplete_user_email_contacts_path %>
			<% end %>
			<%= f.submit 'Add collaborator' %>
		<% end %>		
 	</p>
 	<h4>List of current collaborators</h4>
 	<div id='list-of-users'><%= render :partial => "user", :locals => { :map => @map } %></div> 	
  </div>
  <div class="modal-footer">
    <a href="#" class="btn close" data-dismiss="modal">Close</a>
  </div>
</div>
<% end %>

app/views/maps/_explore.html.erb
<% if @maps.empty? %>
Ops! This is embarrassing... we don't have a public maps yet!
<% else %> 
<ul class="thumbnails">
	<% @maps.each do |map| %>
    <li>
		<div class="thumbnail" style='height:100px;'>
    		<a href='<%= map_path(map) %>'> 
				<img alt="15" height="90" width="90" src="data:image/svg+xml;charset=utf-8;base64,<%= ActiveSupport::Base64.encode64(map.svgdata.to_s) %>" >	 
			</a> 	  
		</div>
    </li>
	<% end %>    
</ul>
<%= link_to('Can\'t wait? Sing in for free and create a new map >>', new_map_path, :class => "btn btn-primary btn-large") unless user_signed_in? %>
<% end %>

app/views/maps/_hud.html.erb
<button id='btn-toggle-hud' class="btn btn-inverse btn-mini" data-toggle="button">
	 <i class='icon-resize-small icon-white'></i>
</button>
<div class='hud' id='node-window'>
	<div id='node-hud'>
		<div class="input-prepend">
			<span class="add-on"><i class='icon-pencil'></i></span>
			<input id='node-title' class='span2' type="text"> </input>
		</div>
		<div class="input-prepend">
			<span class="add-on"><i class='icon-tint'></i></span>
			<input id='node-color' class='span2' type="text"> </input>	
		</div>
		<div class="input-prepend">
			<span class="add-on"><i class='icon-font'></i></span>
			<select class='span2' id='node-font'>			
			</select>		
		</div>
		<div class="input-prepend">
			<a id='node-link' href='#' target='_blank' class='btn btn-inverse btn-mini'>
				<i class='icon-white icon-magnet'></i> 
				Open node link
			</a>
		</div>
		<div class="btn-group " >
		  <button id='btn-bold' class="btn btn-inverse btn-mini" data-toggle="button">
		  	<i class='icon-bold icon-white'></i>
		  </button>
		  <button id='btn-italic' class="btn btn-inverse btn-mini" data-toggle="button">
		  	<i class='icon-italic icon-white'></i>
		  </button>
		  <button id='btn-lock' class="btn btn-inverse btn-mini" data-toggle="button">
		  	<i class='icon-white icon-move'></i>
		  </button>
		  <button id='btn-fold' class="btn btn-inverse btn-mini" data-toggle="button">
		  	<i class='icon-plus icon-white'></i>
		  </button>	
		  <button id='btn-remove' class="btn btn-danger btn-mini">
		  	<i class='icon-remove icon-white'></i>
		  </button>
		</div>

		<div class='hud-wiki'>
			<label>
				Wiki page
				<div id='hud-wiki-content'></div>
				<div class="btn-group">
					<button id='btn-hud-wiki-show' class='btn btn-success'>Show</button>
					<button id='btn-hud-wiki-edit' class='btn btn-primary'>Edit</button>
				</div>
			</label>
		</div>			
	</div>
	<div id='map-hud'>
		Background color
		<div class="input-prepend">			
			<span class="add-on"><i class='icon-tint'></i></span>
			<input id='map-background-color' class='span2' type="text"> </input>	
		</div>
		<div class="btn-group" >
		   <button id='btn-share' class="btn btn-inverse btn-mini" data-toggle="button">
		   	<i class='icon-white icon-eye-open'></i> Map is <span>public</span>
		   </button>
		  <button id='btn-fold' class="btn btn-inverse btn-mini" data-toggle="button">
		  	<i class='icon-plus icon-white'></i>
		  </button>	
		</div>
	</div>
	
</div>

app/views/maps/_ie_is_bad.html.erb
<% if browser.ie? %>
<div class="row" style='height:100px'>
	<div class="offset2 span8" >
		<h2>Sorry but... OpenMindMap doesn't work with Internet Explorer!</h2>
		<p><a href='http://www.google.com/chrome' target='_blank'>Please download and install Google Chrome by clicking here</a></p>
	</div>
</div>
<% end %>

app/views/maps/_list.html.erb
<% if @maps.empty? %>
	Ops! You don't have a maps yet! <%= link_to 'Let\'s start with the first!', new_map_path %>
<% else %> 
	<table class="table table-striped table-condensed">
		<thead>
	         <tr>
	           <th>Title</th>
	           <th>Owner</th>
	           <th>Last modified</th>
	           <th>Actions</th>
	         </tr>
	       </thead>        
		<% @maps.each do |map| %>
			<%= render "map", :map => map %>
		<% end %>	
		<% @shared_maps.each do |map| %>
			<%= render "map", :map => map %>
		<% end %>		
	</table>
	<%= link_to 'New Map >>', new_map_path, :class => "btn btn-primary btn-large" %>	

<% end %>

app/views/maps/_login_options.html.erb
<%= form_for(current_user, :as => :user, :url => session_path(:user), :html => { :class => "well"}) do |f| %>
<%= f.email_field :email, :class=>'input-medium', :placeholder => "Email" %>
<%= f.password_field :password, :class=>'input-medium', :placeholder => "Password" %>
<div><%= f.submit "Login", :class => 'btn' %></div>
<% end %>

<ul class="nav nav-tabs" style = 'width:220px'>
	<li class='active'><a href="#home" data-toggle="tab">Login with</a></li>
	<li><a href="#account" data-toggle="tab">Create account</a></li>
</ul>
<div class="tab-content">
	<div class="tab-pane active" id="home">
		<div class='well'>		
			<div>
				<%= link_to image_tag('social/facebook.png'), user_omniauth_authorize_path(:facebook) %>
				<%= link_to "Facebook", user_omniauth_authorize_path(:facebook) %>
			</div>
			<div>
				<%= link_to image_tag('social/google.png'), user_omniauth_authorize_path(:google_apps) %>
				<%= link_to 'Google', user_omniauth_authorize_path(:google_apps) %>
			</div>
			<div>
				<%= link_to image_tag('social/twitter.png'), user_omniauth_authorize_path(:facebook) %>
				<%= link_to 'Twitter', user_omniauth_authorize_path(:twitter) %>
			</div>
			<div>
				<%= link_to image_tag('social/github.png'), user_omniauth_authorize_path(:github) %>
				<%= link_to "GitHub", user_omniauth_authorize_path(:github) %>
			</div>
			<div>
				<%= link_to image_tag('social/yahoo.png'), user_omniauth_authorize_path(:yahoo, :openid_url => "http://yahoo.com") %>
				<%= link_to "Yahoo", user_omniauth_authorize_path(:yahoo, :openid_url => "http://yahoo.com") %>
			</div>
			<div>
				<%= link_to image_tag('social/windows.png'), user_omniauth_authorize_path(:windowslive, :openid_url => "http://oauth.live.com", :redirect_uri => 'http://openmindmap.me/users/auth/windowslive/callback') %>
				<%= link_to "WindowsLive", user_omniauth_authorize_path(:windowslive, :openid_url => "http://oauth.live.com", :redirect_uri => 'http://openmindmap.me/users/auth/windowslive/callback') %>				
			</div>			
		</div>
	</div>
	<div class="tab-pane" id="account">
		<%= form_for(current_user, :as => :user, :url => registration_path(:user), :html => { :class => "well"}) do |f| %>
		<%= f.email_field :email, :class=>'input-medium', :placeholder => "Email" %>
		<%= f.password_field :password, :class=>'input-medium', :placeholder => "Password" %>
		<%= f.password_field :password_confirmation, :class=>'input-medium', :placeholder => "Confirm password" %>
		<div><%= f.submit "Sign up", :class => 'btn primary' %></div>
		<% end %>  	
	</div>
</div>



        

app/views/maps/_map.html.erb
<div class="span4">
	<tr>
        <td>
        	<%= link_to map.title, edit_map_path(map) %>
			<% if map.users.size > 0  %> 
				<span class="label label-success">Shared (<%= map.users.size %>)</span>
			<% end %>
			<% if map.isPublic  %>
				<span class="label label-info">Public</span>
			<% end %>
		</td>
		<td>
			<% if map.user == current_user %>
			me
			<% else %>
			<%= map.user.email %>
			<% end %>
		</td>
		<td>
			<%= map.updated_at.to_formatted_s(:short)  %>
			<% if map.last_editor && map.last_editor != current_user %>
			<small><%= map.last_editor.email %></small>
			<% else %>
			<small>me</small>
			<% end %>
		</td>
        <td>
        	<%= link_to 'Edit', edit_map_path(map), :class => 'btn btn-success' %>
        	<%= link_to "Delete", map_path(map), :confirm => "Are you sure?", :method => :delete, :class => 'btn btn-danger' %>
        </td>
      </tr>
</div>

app/views/maps/_user.html.erb
<ul id='list-of-collaborators'>
	<% for user in map.users %>
	<li><%= user.email %> <%= link_to 'Revoke', map_contact_path(map, user), :remote => true, :method => :delete, :confirm => "Are you sure?" %></li>
	<% end %>
</li>

app/views/maps/_user_list.html.erb
<ul id='list-of-collaborators'>
	<% for user in map.users %>
	<li><%= user.email %> <%= link_to 'Revoke', map_contact_path(map, user), :remote => true, :method => :delete, :confirm => "Are you sure?" %></li>
	<% end %>
</li>

app/views/maps/edit.html.erb
<% if browser.ie? %>
<%= render 'ie_is_bad' %>
<% else %>
<%= render 'form' %>
<% end %>

app/views/maps/import.html.erb
<h1>Import Freemind Map</h1>
<div class='hero-unit'>
<%= form_tag(maps_import_path, :method => :post, :multipart => true) do %>
  <%= label_tag(:freemind_file, "Select Freemind file from your computer") %>
  <%= file_field_tag :freemind_file %>
  <%= submit_tag :Upload! %>
<% end %>
</div>

app/views/maps/public.html.erb
<% unless user_signed_in? %>
<div class="row-fluid">
	<%= render 'ie_is_bad' %>
	<div class="span12">
		<div class="hero-unit">
			<div class="row-fluid">
				<div class="span8">	
					<div id="myCarousel" class="carousel">
					  <!-- Carousel items -->
					  <div class="carousel-inner">
					    <div class="active item">								
							<div class='offset-home'>
								<%= image_tag 'logo.png' %>
								<h1>Hi, maperino!</h1>
								<p style='width:500px'>
									Welcome to OpenMindMap, a place where you can create your own Mind Map and Dialogue Map! 
									You don't know what is a mind map or a dialogue map? See below for some public maps or 
									<%= link_to "sign in", new_user_registration_path %> to begin mapping!
								</p>
							</div>
					    </div>
					    <div class="item hidden-tablet hidden-phone">
					    	<iframe class='offset-home' width="470" height="264" src="http://www.youtube.com/embed/W8Apl5-xhsA" frameborder="0" allowfullscreen>					    		
					    	</iframe>
					    </div>
					    <div class="item hidden-tablet hidden-phone">
							<%= image_tag 'map_example.png', :size => '470x264', :class => 'offset-home', :style => 'padding-top:60px' %>					    	
					    </div>
					  </div>
					  <!-- Carousel nav -->
					  <a class="carousel-control left hidden-tablet hidden-phone" href="#myCarousel" data-slide="prev">&lsaquo;</a>
					  <a class="carousel-control right hidden-tablet hidden-phone" href="#myCarousel" data-slide="next">&rsaquo;</a>
					</div>									
				</div>
				<div class="span4"><%= render 'login_options' %></div>
			</div>
		</div>
	</div>
</div>


<div class="row hidden-tablet hidden-phone">
	<div class="span4">
		<h2>Hi, maperino!</h2>
		<p>OpenMindMap is a new online collaborative tool for mind mapping and dialogue mapping! 
			It's free for everyone register in this beta period! Please sing in, use it and feedback!</p>
	</div>
	<div class="span4">
		<h2>Mind map</h2>
		<p>A mind map is a diagram used to represent words, ideas, tasks, 
			or other items linked to and arranged around a central key word or idea. 
			<%= link_to :Wikipedia, 'http://en.wikipedia.org/wiki/Mind_map', :target => 'blank' %>. 
		</p>
	</div>
	<div class="span4">
		<h2>Dialogue map</h2>
		<p>Dialogue Mapping™ is a radically inclusive facilitation process that creates a diagram 
			or 'map' that captures and connects participants' comments as a meeting conversation unfolds. 
			<%= link_to 'Cognexus institute', 'http://cognexus.org/id41.htm', :target => 'blank' %></p>
	</div>        
</div>

<% end %>
<div class='page-header hidden-tablet hidden-phone'  style='margin-top:30px'>
	<h1>Explore <small>See what users can do with OpenMindMap</small></h1>
</div>
<div class='hidden-tablet hidden-phone'>
<%= render 'explore' %>
</div>

app/views/maps/show.html.erb
<%= render 'form' %>

app/views/maps/update.js.erb
$("#list-of-users").html("<%= escape_javascript(render(:partial => "maps/user", :locals => { :map => @map })) %>");