config/routes.rb
OpenMindMap::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :news

  resources :bugs

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations => "registrations"}
  
  get "maps/public"
  get "maps/import"
  post "maps/import"
  resources :maps do
    resources :versions
    member do
      post 'share'
      get  'share'     
      post 'event'             
    end
    resources :attachments 
    resources :nodes do 
      resources :attachments 
    end
    resources :contacts

  end
  
  resources :contacts do
    get :autocomplete_user_email, :on => :collection
  end
  
  match ':controller(/:action(/:id(.:format)))'

  root :to => "maps#index"

end

app/models/news.rb
class News < ActiveRecord::Base
  belongs_to :user
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  # GET /news
  # GET /news.json
  def index
    @news = News.all(:order => "created_at DESC", :limit => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @news }
      format.rss { render :layout => false }
    end
  end

  # GET /news/1
  # GET /news/1.json
  def show
    @news = News.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @news }
    end
  end 
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/index.html.erb
<h1>Last OpenMindMap news</h1>

<div class='hero-unit'>
<% @news.each do |news| %>
 <h2><%= news.title %></h2>
 <h3><%= news.created_at %> by <%= news.user.email %></h3>
  <p>
   <%= news.content %>
  </p>
<% end %>
</div>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @news.title %>
</p>

<p>
  <b>Content:</b>
  <%= @news.content %>
</p>

<p>
  <b>User:</b>
  <%= @news.user_id %>
</p>


<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>