config/routes.rb
OpenMindMap::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :news

  resources :bugs

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" , :registrations => "registrations"}
  
  get "maps/public"
  get "maps/import"
  post "maps/import"
  resources :maps do
    resources :versions
    member do
      post 'share'
      get  'share'     
      post 'event'             
    end
    resources :attachments 
    resources :nodes do 
      resources :attachments 
    end
    resources :contacts

  end
  
  resources :contacts do
    get :autocomplete_user_email, :on => :collection
  end
  
  match ':controller(/:action(/:id(.:format)))'

  root :to => "maps#index"

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :user
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_filter :require_login
  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bugs }
    end
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
    @bug = Bug.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bug }
    end
  end

  # GET /bugs/new
  # GET /bugs/new.json
  def new
    @bug = Bug.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bug }
    end
  end

  # GET /bugs/1/edit
  def edit
    @bug = Bug.find(params[:id])
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(params[:bug])

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render json: @bug, status: :created, location: @bug }
      else
        format.html { render action: "new" }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bugs/1
  # PUT /bugs/1.json
  def update
    @bug = Bug.find(params[:id])

    respond_to do |format|
      if @bug.update_attributes(params[:bug])
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy

    respond_to do |format|
      format.html { redirect_to bugs_url }
      format.json { head :ok }
    end
  end
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/views/bugs/_form.html.erb
<%= form_for(@bug) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :status_id %><br />
    <%= f.number_field :status_id %>
  </div>
  <div class="field">
    <%= f.label :assigned_to_user_id %><br />
    <%= f.number_field :assigned_to_user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<h1>Editing bug</h1>

<%= render 'form' %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/index.html.erb
<div class='page-header'>
<h1>Bugs report</h1>
</div>

<table class='table'>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>User</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bugs.each do |bug| %>
  <tr>
    <td><%= bug.title %></td>
    <td><%= bug.content %></td>
    <td><%= bug.user_id %></td>
    <td><%= bug.status_id %></td>
    <td><%= link_to 'Show', bug %></td>
    <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
    <td><%= link_to 'Destroy', bug, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Bug report', new_bug_path, class: 'btn btn-success' %>

app/views/bugs/new.html.erb
<h1>New bug</h1>

<%= render 'form' %>

<%= link_to 'Back', bugs_path %>

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @bug.title %>
</p>

<p>
  <b>Content:</b>
  <%= @bug.content %>
</p>

<p>
  <b>User:</b>
  <%= @bug.user_id %>
</p>

<p>
  <b>Status:</b>
  <%= @bug.status_id %>
</p>

<p>
  <b>Assigned to user:</b>
  <%= @bug.assigned_to_user_id %>
</p>


<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>